git:
  pagers:
    - pager: delta --paging=never --side-by-side --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}";

customCommands:
  - key: "<c-a>" # You can change this keybinding (Ctrl+a in this example)
    context: "files"
    description: "pick AI commit"
    command: 'git commit -m "{{.Form.Msg}}"'
    prompts:
      - type: "menuFromCommand"
        title: "ai Commits"
        key: "Msg"
        command: "lazycommit commit"
        filter: "^(?P<raw>.+)$"
        valueFormat: "{{ .raw }}"
        labelFormat: "{{ .raw | green }}"
gui:
  theme:
    activeBorderColor:
      - "#a6e3a1"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#a6e3a1"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    -"*": "#b4befe"
