exec-once = swaync
exec-once = solaar --window=hide &
exec-once = uwsm app -- hyprsunset

exec-once = /usr/lib/kdeconnectd &
exec-once = /usr/bin/kdeconnect-indicator &!

exec-once = hyprctl dispatch workspace 1
