# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, SEMICOLON, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER ALT SHIFT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER ALT SHIFT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

binddl = SUPER SHIFT, S, suspend, exec, systemctl suspend
bindd = SUPER, Z, Start dictation, exec, voxtype record toggle

# unbind = SUPER, COMMA
# unbind = SUPER SHIFT, COMMA
# unbind = SUPER CTRL, COMMA
# bindd = SUPER, COMMA, Open notification center, exec, swaync-client -t -sw
# bindd = SUPER SHIFT, COMMA, Dismiss all notification, exec, swaync-client -C
# bindd = SUPER CTRL, COMMA, Silence notifications, exec, swaync-client -d

unbing = SUPER, DOWN
unbind = SUPER, UP
unbind = SUPER, LEFT
unbind = SUPER, RIGHT
unbind = SUPER SHIFT, LEFT
unbind = SUPER SHIFT, RIGHT
unbind = SUPER SHIFT, UP
unbind = SUPER SHIFT, DOWN

unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
bindd = SUPER, J, Focus next window, movefocus, d
bindd = SUPER, K, Focus previous window, movefocus, u
bindd = SUPER, L, Focus right window, movefocus, r
bindd = SUPER, H, Focus left window, movefocus, l
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d

unbind = SUPER, N
unbind = SUPER, M
bindd = SUPER, N, Toggle window split, togglesplit, # dwindle
bindd = SUPER, M, Show key bindings, exec, omarchy-menu-keybindings

bindd = SUPER ALT CTRL, G, Gaming Mode, exec, hyprmon --profile gaming
bindd = SUPER ALT CTRL, W, Work Mode, exec, hyprmon --profile work

ubind = SUPER SHIFT, D
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-or-focus ^discord$ "uwsm-app -- discord"

bindd = SUPER, A, Toggle scratchpad, togglespecialworkspace, AI
bindd = SUPER ALT, A, Move window to AI, movetoworkspacesilent, special:AI
