##################### Unbind unused default bindings #####################
unbind = SUPER, N
unbind = SUPER, M
unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
unbing = SUPER, DOWN
unbind = SUPER, UP
unbind = SUPER, LEFT
unbind = SUPER, RIGHT
unbind = SUPER, COMMA
unbind = SUPER ALT, LEFT
unbind = SUPER ALT, RIGHT
unbind = SUPER ALT, UP
unbind = SUPER ALT, DOWN
unbind = SUPER SHIFT, D
unbind = SUPER SHIFT, LEFT
unbind = SUPER SHIFT, RIGHT
unbind = SUPER SHIFT, UP
unbind = SUPER SHIFT, DOWN
unbind = SUPER SHIFT, COMMA
unbind = SUPER CTRL, COMMA
unbind = SUPER CTRL, X

# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, SEMICOLON, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uswm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER ALT SHIFT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-or-focus ^discord$ "uwsm-app -- discord"

# Web app bindings
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER ALT SHIFT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# System bindings
binddl = SUPER SHIFT, S, suspend, exec, systemctl suspend

# Dication binding
bindd = SUPER, Z, Start dictation, exec, voxtype record toggle

# Notification bindings
bindd = SUPER, COMMA, Dismiss latest notification, exec, swaync-client --close-latest
bindd = SUPER ALT, COMMA, Open notification center, exec, swaync-client -t -sw
bindd = SUPER ALT CTRL, COMMA, Dismiss all notifications, exec, swaync-client -C
bindd = SUPER ALT CTRL SHIFT, COMMA, Silence notifications, exec, swaync-client -d

# Window management bindings
bindd = SUPER, J, Focus next window, movefocus, d
bindd = SUPER, K, Focus previous window, movefocus, u
bindd = SUPER, L, Focus right window, movefocus, r
bindd = SUPER, H, Focus left window, movefocus, l
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d

# Groups bindings
bindd = SUPER ALT, L, Move window to group on left, moveintogroup, l
bindd = SUPER ALT, H, Move window to group on right, moveintogroup, r
bindd = SUPER ALT, K, Move window to group on top, moveintogroup, u
bindd = SUPER ALT, J, Move window to group on bottom, moveintogroup, d

# Layout bindings
bindd = SUPER, M, Show key bindings, exec, omarchy-menu-keybindings

# Special workspace bindings
bindd = SUPER, A, Toggle scratchpad, togglespecialworkspace, AI
bindd = SUPER ALT, A, Move window to AI, movetoworkspacesilent, special:AI


