# Essential Nvidia + Wayland variables
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = NVD_BACKEND,direct

# Force NVIDIA ONLY for now to stop dual-GPU DRM panics
env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:01:00.0-card

# Optional: Fix buffer allocation on multi-monitor Nvidia setups
env = AQ_FORCE_LINEAR_BLIT,0
