# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
# source = ~/.config/hypr/conf.d/*.conf

# Float Chromium extension windows and keep PiP floating + pinned
windowrule = float 1, match:class ^(chromium)$, match:title ^(Picture-in-Picture)$
windowrule = pin 1, match:class ^(chromium)$, match:title ^(Picture-in-Picture)$
windowrule = float 1, match:class ^(chromium)$, match:title ^(Extension:.*)$
windowrule = fullscreen 1, match:class ^(cs2)$
windowrule = immediate 1, match:class ^(cs2)$
windowrule = workspace 1 silent, match:class ^(cs2)$
windowrule = workspace 1 silent, match:class ^(gamescope)$

general {
    allow_tearing = true
}
misc {
  vrr = 2
  mouse_move_enables_dpms = false
}


monitor=HDMI-A-1,disable
monitor=DP-1,3840x2160@240.08,3440x720,1.00
monitor=DP-2,disable
monitor=DP-3,disable