general {
    gaps_in = 5
    gaps_out = 12
    border_size = 4
}

decoration {
    rounding = 10
    active_opacity = 1.1
    inactive_opacity = 1.1
}
layout {
  # single_window_aspect_ratio = 1.75 1
}
