# vim: set ft=hyprlang:
general {
  gaps_in = 5
  gaps_out = 12
  border_size = 4
  layout = scrolling
  snap {
    enabled = true
    respect_gaps = true
  }
}
decoration {
  rounding = 10
  active_opacity = 1.1
  inactive_opacity = 1.1
}
scrolling {
  fullscreen_on_one_column = true
  column_width = .75
  follow_focus = true
  focus_fit_method = 1
  follow_min_visible = 0.0
}
layout {
  # single_window_aspect_ratio = 1.75 1
}
